- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars
    templatekey: 'https://raw.githubusercontent.com/sangaml/ARM_Ansible_IAAS/master/keyvault.json'
    paramskey: 'https://raw.githubusercontent.com/sangaml/ARM_Ansible_IAAS/master/keyvault.parameters.json'
    
    #sqlserver: 'https://raw.githubusercontent.com/sangaml/ARM_Ansible_IAAS/master/ARMtemplate-newVM.json'
    #sqlparamsLink: 'https://raw.githubusercontent.com/sangaml/ARM_Ansible_IAAS/master/sql-server.parameters.json'
    
    
  tasks:
  - name: Deploy vault key template
    azure_rm_deployment:
        state: present
        resource_group_name: '{{ resgrp }}'
        # location seems to be not optional
        location: '{{ location }}'
        template_link: '{{ templatekey }}'
        parameters_link: '{{ paramskey }}' 
        
- hosts: localhost      
  vars:
      mongo: 'https://raw.githubusercontent.com/sangaml/testarm/master/mongo.json'
      mongoparams: 'https://raw.githubusercontent.com/sangaml/testarm/master/mongo.parameters.json'
  tasks:      
    - name: Deploy mongo template
      azure_rm_deployment:
        state: present
        resource_group_name: '{{ resgrp }}'
        # location seems to be not optional
        location: '{{ location }}'
        template_link: '{{ mongo }}'
        parameters_link: '{{ mongoparams }}'
        
- hosts: localhost
  vars:
      templateLink: 'https://raw.githubusercontent.com/sangaml/ARM_Ansible_IAAS/master/addedextention.json'
  tasks:
    - name: Deploy Iaas ARM template
      azure_rm_deployment:
        state: present
        resource_group_name: '{{ resgrp }}'
        # location seems to be not optional
        location: '{{ location }}'
        template_link: '{{ templateLink }}'
