- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create instance of Key Vault
      azure_rm_keyvault:
          resource_group: '{{ rsgrp }}'
          vault_name: samplekeyvault
          enabled_for_deployment: yes
          vault_tenant: '{{ tenantId }}'
          sku:
            name: standard
          access_policies:
              - tenant_id: '{{ tenantId }}'
                object_id: '{{ objectId }}'
                keys:
                     - get
                     - list
    - name: Create a secret
      azure_rm_keyvaultsecret:
         secret_name: sangamsec
         secret_value: Sangam@lonkar14
         keyvault_uri: https://samplekeyvault.vault.azure.net/
         tags:
                testing: testing
                delete: never
