- name: CREATE ARM Key Vault Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars
    templateLink: 'https://raw.githubusercontent.com/sangaml/ARM_Ansible_IAAS/master/KeyVaultSetup.json'
    # No parameters required for this template
    paramsLink: 'https://raw.githubusercontent.com/sangaml/ARM_Ansible_IAAS/master/KeyVaultSetup.parameters.json'
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: '{{ resgrp }}'
        # location seems to be not optional
        location: '{{ location }}'
        template_link: '{{ templateLink }}'
        parameters_link: '{{ paramsLink }}'
